import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmokeyCursor from "@/components/lightswind/smokey-cursor";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
         <SmokeyCursor />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
